### ISSUE TITLE
Issue added by version 5.0.0

### ISSUE THREAD

**Issue by villander** [RobbieTheWagner/ember-flatpickr#1977]
When you update from version 4.x to 5.0.0 using Ember.js 5 you'll see a weird issue in the acceptance tests that use `setFlatpickrDate` helper

<img width="793" alt="image" src="https://github.com/RobbieTheWagner/ember-flatpickr/assets/10222774/86073a78-5a9a-4f38-be7a-ac76e270a782">

**Comment by RobbieTheWagner** [comment]
Hmm, thanks for letting me know @villander! Does flatpickr otherwise work fine for you and is just a testing issue?

**Comment by villander** [comment]
Yes, @RobbieTheWagner it's just a testing issue for acceptance tests, for the component tests we're good. I see this repo does not have acceptance tests which made this issue pass through the last release without notice.

**Comment by RobbieTheWagner** [comment]
> Yes, @RobbieTheWagner it's just a testing issue for acceptance tests, for the component tests we're good. I see this repo does not have acceptance tests which made this issue pass through the last release without notice.

Interesting, I am not sure what might be happening. Would you possibly be able to add a basic acceptance test that reproduces the issue?

**Comment by AmauryD** [comment]
I've encountered the same problem in one of my apps, will take a look into it soon.

**Comment by AmauryD** [comment]
Don't have a lot of time atm, but i least i have a quick fix @villander .

Seems to be related to @ember/test-helpers. We're currently using version 2.7, which is causing issues. Works fine with 3.x. 

A temporary fix is to pin "@ember/test-helpers" to version 3.x.

My PNPM overrides: 

```ts
  "pnpm": {
    "overrides": {
      "@ember/test-helpers": "^3.2.1"
    }
  },
```

**Comment by RobbieTheWagner** [comment]
@AmauryD would updating to 3.x here fix that then? https://github.com/RobbieTheWagner/ember-flatpickr/blob/main/ember-flatpickr/package.json#L45

**Comment by AmauryD** [comment]
> @AmauryD would updating to 3.x here fix that then? https://github.com/RobbieTheWagner/ember-flatpickr/blob/main/ember-flatpickr/package.json#L45

I tried, but we lose compatibility with Ember 4.4. Actually, this release is unsupported since 
May 2023. Should we drop the support or do we need to investigate further ?

**Comment by villander** [comment]
@RobbieTheWagner this issue wasn't fixed with this latest release, nor with this workaround. 

https://github.com/RobbieTheWagner/ember-flatpickr/issues/1977#issuecomment-1919959722

**Comment by AmauryD** [comment]
Can you provide an example repo or more details ?
The problem is fixed using version 7 in my packages

**Comment by AmauryD** [comment]
Ok, the actual problem seems to be a mismatch in `@ember/test-helpers` versions. If you match exactly the version of the addon (^3.0.0) it works. What's your `@ember/test-helpers` version ?

**Comment by RobbieTheWagner** [comment]
I suspect the issue is fixed but perhaps you need to run `pnpm dedupe @ember/test-helpers` in your monorepo or something @villander. Can you try that?

**Comment by villander** [comment]
After dedupe, it made things worse @RobbieTheWagner breaking the build

```
Build Error (PackagerRunner) in node_modules/.pnpm/ember-animated@2.0.0_@babel+core@7.23.9_@ember+test-helpers@3.3.0_@glint+environment-ember-lo_73frxrh6fy5tz2g552pkrytcqi/node_modules/ember-animated/dist/-private/bounds.js

Module build failed (from ../../../../../../../../Users/villander/Projects/project/web-ui/node_modules/.pnpm/thread-loader@3.0.4_webpack@5.90.3/node_modules/thread-loader/dist/cjs.js):
Thread Loader (Worker 3)
$TMPDIR/embroider/2012c7/node_modules/.pnpm/ember-animated@2.0.0_@babel+core@7.23.9_@ember+test-helpers@3.3.0_@glint+environment-ember-lo_73frxrh6fy5tz2g552pkrytcqi/node_modules/ember-animated/dist/-private/bounds.js/bounds.js: Static class blocks are not enabled. Please add `@babel/plugin-transform-class-static-block` to your configuration.
```
