### ISSUE TITLE
Error: Could not find module `flatpickr` imported from `ember-flatpickr/components/ember-flatpickr` after upgrading from v4.0.0 to v7.0.0

### ISSUE THREAD

**Issue by paddor** [RobbieTheWagner/ember-flatpickr#2062]
In an addon (and app) I'm using Ember v5.4.0 and upgraded Ember-flatpickr from v4.0.0 to v7.0.0. Now I'm getting this error:

```
Error: Could not find module `flatpickr` imported from `ember-flatpickr/components/ember-flatpickr`
```

I tried adding `"flatpickr": "^4.6.13"` to my app's dependencies in `package.json` but that didn't help. Any ideas?

**Comment by RobbieTheWagner** [comment]
@paddor apologies for the delay in responding. flatpickr does need to be added to your app, but it should work. Do you have ember-auto-import and/or embroider in your app? 

CC @AmauryD I assume everything is working in your app? Not sure if you know what might be going on.

**Comment by AmauryD** [comment]
Everything seems to be working fine on my end. I tested it on a fresh repo using npm, yarn, and pnpm with both Embroider and Classic mode. It might be an issue with the package manager installation ?

**Comment by paddor** [comment]
> @paddor apologies for the delay in responding. flatpickr does need to be added to your app, but it should work. Do you have ember-auto-import and/or embroider in your app? 

Thanks. Maybe it was missing in the app. I'm afk for two weeks. Will try afterwards. Thanks again.

**Comment by paddor** [comment]
Can confirm, ember-flatpickr 8.0.1 (used in an addon) works after `ember install ember-flatpickr` in the app. Including the default stylesheet from the addon's SCSS file works with

```scss
@import "flatpickr/dist/flatpickr";
```

Thanks for the help.

**Comment by RobbieTheWagner** [comment]
Glad you got it working @paddor! `ember-flatpickr` should be installed anywhere it is used I think.
