### ISSUE TITLE
Localization docs

### ISSUE THREAD

**Issue by RobbieTheWagner** [RobbieTheWagner/ember-flatpickr#2063]
@AmauryD should we delete the localization docs now? Since we support dynamically importing from a string, I think we should not need to support passing locale objects or custom locale configs past that?

**Comment by AmauryD** [comment]
We can still allow users the freedom to choose how they import locales, as it does not have any maintenance cost for ember-flatpicker. However, I agree that we can cleanup/improve the localization documentation regarding locales.
