### ISSUE TITLE
Upgrading to v7 or v8 results in "Can't resolve 'flatpickr/dist/l10n'"

### ISSUE THREAD

**Issue by ecit-bbracke** [RobbieTheWagner/ember-flatpickr#2099]
When upgrading to v7 or v8 I get the error "Can't resolve "'flatpickr/dist/l10n'" during build.

This is without embroider.

**Comment by RobbieTheWagner** [comment]
@ecit-bbracke do you have flatpickr installed? It is a peerDep.

**Comment by ecit-bbracke** [comment]
If I install it as a peerDependency (4.6.13"), I get:
Module not found: Error: Can't resolve 'flatpickr' in '/home/bent/Projekter/boel/node_modules/ember-flatpickr/dist/components/ember-flatpickr.js'

**Comment by RobbieTheWagner** [comment]
@ecit-bbracke do you have ember-auto-import v2 installed or are you using embroider? It may be required that you have one or the other.

**Comment by ecit-bbracke** [comment]
Sorry for the delay.
I have fixed the problem, by fixing other dependency problems. don't what it was specificly.
